<?php
//Somunachimso Bernard Nzenwa
require_once('Template/header.phtml') ?>

<h1>Hi, I'm Somunachimso Nzenwa.</h1>
<p>A passionate programmer who finds enjoyment and fulfillment from the journey of creating software. I am currently open to engineering roles and based in the UK. &#x1F4CD;</p>
<img src="../images/profile_picture.jpg" alt="Profile Picture">
<button>Download CV</button>
<br>
<div class="wrapper">

    <div class="button">
        <div class="icon">
            <i class="fa fa-github"></i>
        </div>
    </div>

    <div class="button">
        <div class="icon">
            <i class="fa fa-linkedin"></i>
        </div>
    </div>

</div>
<?php
require_once('Template/footer.phtml') ?>