<!-- Header for the web pages
//Somunachimso Bernard Nzenwa_AGG801_@00652263
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Somuna's Portfolio">
    <meta name="author" content="Somunachimso Bernard Nzenwa">

<!--    JavaScript file-->
    <script src="/js/myscripts.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!--    CSS file    -->
    <link href="/css/styles.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title><?php echo $view->pageTitle; ?></title>
</head>
<!--<div class="row">-->
<!--    <div id="title" class="col-xs-12 col-lg-12">-->
<!--        <h1 id="text-left">-->
<!--            <a id="text-left">LIGHTNING CHARGERS</a>-->
<!--        </h1>-->
<!--    </div>-->
<!--</div>-->
<nav>
    <li><a href="career.php">Profile</a></li>
    <li><a href="projects.php">Search</a></li>
    <li><a href="research.php">Search</a></li>
    <li><a href="skills.php">Profile</a></li>
</nav>
<br>
<body role="document">
    <div class="container">